[project]
name = "Master Thesis, Imperial College London"
version = "0.1.0"
description = "Master Thesis, Imperial College London"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
authors = [
  {name = "Swapnil Kumar", email = "swapnil.kumar22@alumni.imperial.ac.uk"}
]
maintainers = [
  {name = "Swapnil Kumar", email = "swapnil.kumar22@alumni.imperial.ac.uk"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
  "pytest"
]

[tool.setuptools]
packages = ["src"]

